# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"my_core_helper_function": "00_core.ipynb",
         "in_notebook": "00_core.ipynb",
         "load_and_cache_raw_data": "01_datapipe.ipynb",
         "lookup_lat_lon_from_placename": "02_geo.ipynb",
         "TITANIC_DATA_FILE": "88_app.ipynb",
         "AUTHOR_INFO": "88_app.ipynb",
         "APP_NAME": "88_app.ipynb",
         "SideBar": "88_app.ipynb",
         "create_sidebar": "88_app.ipynb",
         "app_mainscreen": "88_app.ipynb",
         "notebook_mainscreen": "88_app.ipynb",
         "sb": "88_app.ipynb",
         "df": "88_app.ipynb"}

modules = ["core.py",
           "datapipe.py",
           "geo.py",
           "app.py"]

doc_url = "https://mjboothaus.github.io/hello_titanic/"

git_url = "https://github.com/mjboothaus/hello_titanic/tree/master/"

def custom_doc_links(name): return None
