# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/02_geo.ipynb (unless otherwise specified).

__all__ = ['lookup_lat_lon_from_placename']

# Cell
from geopy.geocoders import Nominatim
def lookup_lat_lon_from_placename(place):
    lat = None
    lon = None
    geolocator = Nominatim(user_agent="DataBooth")
    try:
        location = geolocator.geocode(place)
        lat = location.latitude
        lon = location.longitude
    except Exception as e:
        print(e)
    return lat, lon